### ISSUE TITLE
SPIKE: New DB Schemas - Part 1

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#540]
- [x] Create an overview of the DB Schemas
- [x] Create a diagram
- [x] Discuss the schemas @stacysealky  @Enubia

**Comment by stacysealky** [comment]
![Image](https://github.com/donategifts/donategifts/assets/26069780/a692d195-6892-49ae-9f90-fd3d2351d0ef)

**Comment by nick-w-nick** [comment]
We discussed the MySQL vs Postgres decision over discord. Planetscale  actually charges by rows read rather than read operations. Due to this, the pricing is no longer sustainable long-term and was originally the only reason for considering MySQL.

Due to this conclusion we have decided to go with Postgres as planned and are currently determining a suitable hosting solution (Self vs Managed) and will update once we have come to a decision, suggestions are welcome.

**Comment by Enubia** [comment]
Local development setup (docker container) for Postgres is created and can be turned on by activating the specific container and volume in `docker-commpose.yml`.

An init script is automatically mounted to create the database according to the provided diagram.

**Comment by stacysealky** [comment]
https://github.com/kysely-org/kysely
https://neon.tech/

Isolate ORM from code base by using DAL (data access layer)

Need to write migration script - maybe @Enubia 👯
